### ISSUE TITLE
XOA container does not start

### ISSUE THREAD

**Issue by lukeshaughnessy** [yobasystems/alpine-xen-orchestra#4]
Running Ubuntu 16.04
Pulling latest with docker-compose

root@vagrant:~# docker logs 73f2e0c3fbd9
yarn run v1.3.2
$ node bin/xo-server
Mon, 18 Dec 2017 15:59:52 GMT app-conf /app/xo-server/config.json
Mon, 18 Dec 2017 15:59:52 GMT app-conf /etc/xo-server/config.yaml
2017-12-18T15:59:52.278Z xo:main Configuration loaded.
2017-12-18T15:59:52.283Z xo:main Web server listening on http://[::]:8080
2017-12-18T15:59:52.284Z xo:main User changed to xenorchestra
2017-12-18T15:59:52.382Z xo:perf blocked for 25ms
[WARN] start error: Error: spawn vgchange ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Segmentation fault (core dumped)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 139.

**Comment by BastienM** [comment]
Hi @lukeshaughnessy ,

That is something I also noticed after my PR got merged.
I got an error as well : 

```
docker run --rm --name xoa --link xoa-redis.service:redis -p 8080:8080 -e NODE_ENV=production -v /opt/xoa/server/data:/app/data yobasystems/alpine-xen-orchestra:amd64 yarn start
Unable to find image 'yobasystems/alpine-xen-orchestra:amd64' locally
amd64: Pulling from yobasystems/alpine-xen-orchestra
1160f4abea84: Already exists
78054129aedf: Already exists
9f56a0cbbf04: Already exists
fa97165699ec: Pull complete
5b801203a527: Pull complete
61c78e55df4d: Pull complete
7e31bb89e455: Pull complete
de13f8ce0aaa: Pull complete
160d5b7e7ba3: Pull complete
Digest: sha256:7bf5ecd81e4ebd15eed710c2287bbaaa8cd75a67480d5bcfb7ca795ee7a64d16
Status: Downloaded newer image for yobasystems/alpine-xen-orchestra:amd64
yarn run v1.3.2
$ node bin/xo-server
module.js:538
    throw err;
    ^

Error: Cannot find module './dist'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/xo-server/index.js:11:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/xo-server/bin/xo-server:31:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

In the meantime you can use my image `bastienm/alpine-xoa`.
It should works fine till we got that fixed.


/ping @dominictayloruk

**Comment by dominictayloruk** [comment]
This is something to do with permissions and the data in the bind mounted folder in the xoa container. If you delete the leveldb folder and restart then it runs. Maybe this volume mapping isn't needed as persistence resides in the redis instance and environment variables should be passed at container run time. Also this container is running Alpine version 3.6 rather than the aged 3.4. I've also just added Alpine 3.7 so i see how that builds.
